server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: product-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${DATABASE_USERNAME:service_orders}
    password: ${DATABASE_PASSWORD:service_orders_dev}

    hikari:
      maximum-pool-size: ${DATABASE_POOL_SIZE:10}
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always