{
  "type": "record",
  "name": "InventoryReserved",
  "namespace": "com.stoliar.events.inventory",
  "fields": [
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "userId",
      "type": "string"
    },
    {
      "name": "reserved",
      "type": "boolean"
    },
    {
      "name": "reason",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "createdAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}